### ISSUE TITLE
<INPUT-FILE>

### ISSUE THREAD

**Issue by ZaxCZ** [yago-naga/aida#13]
https://github.com/yago-naga/aida#hands-on-command-line-call-example

Could you please specify, how should I enter the path of Input File with that command? I tried redirecting input with < (didn't work). And I also tried putting a full path or just a file name at the end
`java -Xmx4G -cp target/aida-2.X.X-jar-with-dependencies.jar mpi.aida.CommandLineDisambiguator -t GRAPH -s -i input-file`
What is the correct way of doing so? Thank you.

**Comment by hoffart** [comment]
Sorry about that, the README is a bit misleading here. Leave out -s and it should work (-s treats the input specified with -i as string). I also updated the README, hopefully it is more understandable now.
Cheers.

**Comment by ZaxCZ** [comment]
Thanks for your quick response.
