### ISSUE TITLE
DMap Usage with AIDA

### ISSUE THREAD

**Issue by Sherylss** [yago-naga/aida#15]
Hi, 

I'm trying to create DMaps instead of using the aida postgres db. I cannot find the mpi.aida.datapreparation.PrepareData file that needs to be run in order to create the DMaps. Can you please let me know how this is done then? 

I also use the YAGO_FULL database to get other properties of entities. Is it possible to create DMaps for it as well? 

Thanks

**Comment by hoffart** [comment]
Hi,

you can get a working DMap here [1]. The code for creating it is not (yet) published.

Cheers
Johannes

[1] http://resources.mpi-inf.mpg.de/yago-naga/aida/download/entity-repository/AIDA_entity_repository_2014-01-02v10_dmap.tar.bz2
