### ISSUE TITLE
YAGO-AIDA dataset and CoNNLReader

### ISSUE THREAD

**Issue by Agupta00** [yago-naga/aida#28]
Hi, 

I want to test Aida on the AIDA-YAGO2-dataset.tsv file, yet when I Disambiguate the dataset it only runs over a small portion of the dataset, from Document '1304testb Turkey' to 1393testb SOCCER. How do I run on the entire dataset?

My code:

CoNLLReader reader = new CoNLLReader("path/to/AIDA-YAGO2-dataset.tsv");

		for (String key : reader.getAllDocIds()) {
			PreparedInput input = reader.getPreparedInputForDocId(key);
			PriorOnlyDisambiguationSettings setting = new PriorOnlyDisambiguationSettings();
			Disambiguator d = new Disambiguator(input, setting);
			DisambiguationResults results = d.disambiguate();

			for (ResultMention rm : results.getResultMentions()) {
				  ResultEntity re = results.getBestEntity(rm);
				  System.out.println(rm.getMention() + " -> " + re);
				}
		}

**Comment by Agupta00** [comment]
My mistake, turns out the console just trimmed its output.

**Comment by dingdingdang** [comment]
Hi A,

Hope you had a good weekend.
I am wondering that have you reproduced the results on CoNLL-AIDA data?
